### ISSUE TITLE
Test build Linux using docker fails

### ISSUE THREAD

**Issue by gmacario** [eelcocramer/node-bluetooth-serial-port#229]
Hello,

I followed the instructions at section "Test build Linux using docker" of README.md 

```bash
docker build -t bluetooth-serial-port .
```

but was unable to complete Step 6/6 "RUN npm install --unsafe-perm":

```
gpmacario@nemo:~/github/gmacario/node-bluetooth-serial-port (master)$ docker build -t bluetooth-serial-port .
Sending build context to Docker daemon  984.6kB
Step 1/6 : FROM node:latest
 ---> 7354979df4ec
Step 2/6 : RUN apt-get update
 ---> Using cache
 ---> 49f6abc5cb12
Step 3/6 : RUN apt-get install -y build-essential libbluetooth-dev
 ---> Using cache
 ---> 033333f4e474
Step 4/6 : ADD . node-bluetooth-serial-port
 ---> Using cache
 ---> 7d68f99b6a69
Step 5/6 : WORKDIR node-bluetooth-serial-port
 ---> Using cache
 ---> d9a0f0debb57
Step 6/6 : RUN npm install --unsafe-perm
 ---> Running in 292c6b5f71bc

> bluetooth-serial-port@2.2.6 install /node-bluetooth-serial-port
> node-gyp configure build

make: Entering directory '/node-bluetooth-serial-port/build'
  CXX(target) Release/obj.target/BluetoothSerialPort/src/linux/BluetoothSerialPort.o
  CXX(target) Release/obj.target/BluetoothSerialPort/src/linux/DeviceINQ.o
../src/linux/DeviceINQ.cc: In static member function 'static void DeviceINQ::EIO_AfterSdpSearch(uv_work_t*)':
../src/linux/DeviceINQ.cc:139:28: warning: 'v8::Local Nan::Callback::Call(int, v8::Local*) const' is deprecated [-Wdeprecated-declarations]
     baton->cb->Call(1, argv);
                    ^
In file included from ../src/linux/DeviceINQ.cc:14:0:                                                                                                                        ../node_modules/nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local argv[]) const {
                   ^~~~                                                                                                                                                                      ../src/linux/DeviceINQ.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE DeviceINQ::InquireSync(Nan::NAN_METHOD_ARGS_TYPE)':
../src/linux/DeviceINQ.cc:251:26: warning: 'v8::Local Nan::Callback::Call(int, v8::Local*) const' is deprecated [-Wdeprecated-declarations]
      found->Call(2, argv);
       ^
In file included from ../src/linux/DeviceINQ.cc:14:0:
../node_modules/nan/nan.h:1740:3: note: declared here
Call(int argc, v8::Local argv[]) const {
^~~~                                                                                                                                                                      ../src/linux/DeviceINQ.cc:255:27: warning: 'v8::Local Nan::Callback::Call(int, v8::Local*) const' is deprecated [-Wdeprecated-declarations]
callback->Call(0, argv);
^
In file included from ../src/linux/DeviceINQ.cc:14:0:
../node_modules/nan/nan.h:1740:3: note: declared here
Call(int argc, v8::Local argv[]) const {
^~~~
../src/linux/DeviceINQ.cc: In member function 'virtual void InquireWorker::HandleOKCallback()':
../src/linux/DeviceINQ.cc:284:26: warning: 'v8::Local Nan::Callback::Call(int, v8::Local*) const' is
deprecated [-Wdeprecated-declarations]
found->Call(2, argv);
^
In file included from ../src/linux/DeviceINQ.cc:14:0:
../node_modules/nan/nan.h:1740:3: note: declared here
Call(int argc, v8::Local argv[]) const {
^~~~
../src/linux/DeviceINQ.cc:288:27: warning: 'v8::Local Nan::Callback::Call(int, v8::Local*) const' is deprecated [-Wdeprecated-declarations]
callback->Call(0, argv);
^
In file included from ../src/linux/DeviceINQ.cc:14:0:
../node_modules/nan/nan.h:1740:3: note: declared here
Call(int argc, v8::Local argv[]) const {
^~~~
CXX(target) Release/obj.target/BluetoothSerialPort/src/linux/BTSerialPortBinding.o
../src/linux/BTSerialPortBinding.cc: In static member function 'static void
BTSerialPortBinding::EIO_AfterConnect(uv_work_t*)':
../src/linux/BTSerialPortBinding.cc:83:32: warning: 'v8::Local Nan::Callback::Call(int, v8::Local*) const' is deprecated [-Wdeprecated-declarations]
baton->cb->Call(0, NULL);
^
In file included from ../src/linux/BTSerialPortBinding.cc:14:0:
../node_modules/nan/nan.h:1740:3: note: declared here
Call(int argc, v8::Local argv[]) const {
^~~~
../src/linux/BTSerialPortBinding.cc:90:33: warning: 'v8::Local Nan::Callback::Call(int, v8::Local*) const' is deprecated [-Wdeprecated-declarations]
baton->ecb->Call(1, argv);
^
In file included from ../src/linux/BTSerialPortBinding.cc:14:0:
../node_modules/nan/nan.h:1740:3: note: declared here
Call(int argc, v8::Local argv[]) const {
^~~~
../src/linux/BTSerialPortBinding.cc: In static member function 'static void BTSerialPortBinding::EIO_Write(uv_work_t*)':
../src/linux/BTSerialPortBinding.cc:114:69: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
int bytesSent = write(rfcomm->s, data->bufferData+data->result, bytesToSend);
^~~~~~
../src/linux/BTSerialPortBinding.cc: In static member function 'static void BTSerialPortBinding::EIO_AfterWrite(uv_work_t*)':
../src/linux/BTSerialPortBinding.cc:143:33: warning: 'v8::Local Nan::Callback::Call(int, v8::Local*) const' is deprecated [-Wdeprecated-declarations]
       data->callback->Call(2, argv);
^
In file included from ../src/linux/BTSerialPortBinding.cc:14:0:
../node_modules/nan/nan.h:1740:3: note: declared here
Call(int argc, v8::Local argv[]) const {
^~~~
../src/linux/BTSerialPortBinding.cc: In static member function 'static void BTSerialPortBinding::EIO_AfterRead(uv_work_t*)':
../src/linux/BTSerialPortBinding.cc:206:117: error: no matching function for call to 'v8::Object::Get(v8::Local)'
Local bufferConstructor = Local::Cast(globalObj->Get(Nan::New("Buffer").ToLocalChecked()));                                                                                                                                                                          ^
In file included from ../src/linux/BTSerialPortBinding.cc:12:0:
/root/.cache/node-gyp/13.5.0/include/node/v8.h:3594:43: note: candidate: v8::MaybeLocal v8::Object::Get(v8::Local, v8::Local)
V8_WARN_UNUSED_RESULT MaybeLocal Get(Local context,                                                                                                                                                  ^~~
/root/.cache/node-gyp/13.5.0/include/node/v8.h:3594:43: note:   candidate expects 2 arguments, 1 provided
/root/.cache/node-gyp/13.5.0/include/node/v8.h:3597:43: note: candidate: v8::MaybeLocal v8::Object::Get(v8::Local, uint32_t)
V8_WARN_UNUSED_RESULT MaybeLocal Get(Local context,
^~~
/root/.cache/node-gyp/13.5.0/include/node/v8.h:3597:43: note:   candidate expects 2 arguments, 1 provided
../src/linux/BTSerialPortBinding.cc:215:28: warning: 'v8::Local Nan::Callback::Call(int, v8::Local*) const' is deprecated [-Wdeprecated-declarations]
baton->cb->Call(2, argv);
^
In file included from ../src/linux/BTSerialPortBinding.cc:14:0:
../node_modules/nan/nan.h:1740:3: note: declared here
Call(int argc, v8::Local argv[]) const {
^~~~
../src/linux/BTSerialPortBinding.cc: In static member function 'static void BTSerialPortBinding::Init(v8::Local)':
../src/linux/BTSerialPortBinding.cc:242:103: error: no matching function for call to 'v8::Object::Set(v8::Local, v8::Local)'
target->Set(Nan::New("BTSerialPortBinding").ToLocalChecked(), t->GetFunction(ctx).ToLocalChecked());
^
In file included from ../src/linux/BTSerialPortBinding.cc:12:0:
/root/.cache/node-gyp/13.5.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe v8::Object::Set(v8::Local, v8::Local, v8::Local)    V8_WARN_UNUSED_RESULT Maybe Set(Local context,                                                                                                                                                  ^~~                                                                                                                                     /root/.cache/node-gyp/13.5.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/root/.cache/node-gyp/13.5.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe v8::Object::Set(v8::Local, uint32_t, v8::Local)
V8_WARN_UNUSED_RESULT Maybe Set(Local context, uint32_t index,                                                                                                                                  ^~~                                                                                                                                     /root/.cache/node-gyp/13.5.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
../src/linux/BTSerialPortBinding.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE BTSerialPortBinding::Read(Nan::NAN_METHOD_ARGS_TYPE)':                    ../src/linux/BTSerialPortBinding.cc:392:25: warning: 'v8::Local Nan::Callback::Call(int, v8::Local*) const' is deprecated [-Wdeprecated-declarations]
nc->Call(2, argv);
^
In file included from ../src/linux/BTSerialPortBinding.cc:14:0:
../node_modules/nan/nan.h:1740:3: note: declared here
Call(int argc, v8::Local argv[]) const {
^~~~
BluetoothSerialPort.target.mk:115: recipe for target 'Release/obj.target/BluetoothSerialPort/src/linux/BTSerialPortBinding.o' failed
make: Leaving directory '/node-bluetooth-serial-port/build'
make: *** [Release/obj.target/BluetoothSerialPort/src/linux/BTSerialPortBinding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-72-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /node-bluetooth-serial-port
gyp ERR! node -v v13.5.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bluetooth-serial-port@2.2.6 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bluetooth-serial-port@2.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-07T11_21_03_350Z-debug.log
The command '/bin/sh -c npm install --unsafe-perm' returned a non-zero code: 1
gpmacario@nemo:~/github/gmacario/node-bluetooth-serial-port (master)$
```

Reproduced on

- Ubuntu 18.04.3 LTS 64-bit
- Docker version 19.03.5, build 633a0ea838
- latest commit on master branch (89e62bc5fb1a6763fd3711505d4583efb4bd5449)

**Comment by eelcocramer** [comment]
Thank you for the report.

I can reproduce this. The quick fix is to change the base image to `node:lts`. I will push a fix that has this change soon.

**Comment by gmacario** [comment]
Hello @eelcocramer,
Thanks for your super-fast response!
II confirm that building against node:LTS (12.14.1 as of today) works fine and produces only warnings during "npm install". 

Just wondering whether either you or someone else has any plans for making this component install on Node 13...

**Comment by eelcocramer** [comment]
Currently I only support the LTS versions of node. In the past I’ve found the current versions to be to unstable to work with.
